api:
  base: "https://online-serving-feeds-api-testing-810737581373.asia-southeast1.run.app/"
  route: "/recommendations"
search:
  endpoint_id: "projects/810737581373/locations/asia-southeast1/indexEndpoints/148170186959093760"
  deployed_index_id: "feeds_20k_deployed"
request:
  include_endpoint_fields: false
evaluation:
  top_k: 10
timeout_seconds: 60
data:
  groundtruth_csv: "test_metrics/data/ground_truth_gold_top10.csv"
output:
  csv: "test_metrics/data/recommendation_metrics_results.csv"
